import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowLeft,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {projects} from './content';
import {useLanguage,useText} from './site';
export function Gallery({filters=false}:{filters?:boolean}){const lang=useLanguage();const t=useText(); const [filter,setFilter]=useState('all'); const [selected,setSelected]=useState<number|null>(null);const index=lang==='ar'?1:0;const project=selected===null?null:projects[selected];const step=(n:number)=>setSelected(v=>v===null?null:(v+n+projects.length)%projects.length);
 useEffect(()=>{if(selected===null)return;const key=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')step(1);if(e.key==='ArrowLeft')step(-1)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[selected]);
 return <>{filters&&<div className="project-filters">{([['all','Tous les projets','كل المشاريع'],['architecture','Architecture','عمارة'],['interior','Design intérieur','تصميم داخلي'],['plans','Plans & 3D','مخططات وثلاثي الأبعاد']] as const).map(([value,fr,ar])=><Button variant="ghost" key={value} className={filter===value?'filter active':'filter'} onClick={()=>setFilter(value)} aria-pressed={filter===value}>{t(fr,ar)}</Button>)}</div>}<div className="project-grid">{projects.map((p,i)=>(filter==='all'||filter===p.type)&&<article key={p.image} className="project-item"><Button variant="ghost" className="project-image" onClick={()=>setSelected(i)} aria-label={t('Voir le projet : ','عرض المشروع: ')+p.title[index]}><img src={p.image} alt={p.title[index]} loading="lazy"/><span className="project-open"><ArrowUpRight size={22}/></span></Button><div className="project-label"><div><h3>{p.title[index]}</h3><p>{p.caption[index]}</p></div><span>0{i+1}</span></div></article>)}</div><Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="lightbox" aria-describedby="project-caption" onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft')e.stopPropagation()}}>{project&&<><DialogTitle>{project.title[index]}</DialogTitle><DialogDescription id="project-caption">{project.caption[index]}</DialogDescription><img className="lightbox-image" src={project.image} alt={project.title[index]}/><div className="lightbox-controls"><Button variant="ghost" size="icon" onClick={()=>step(-1)} aria-label={t('Projet précédent','المشروع السابق')}><ArrowLeft/></Button><span>{String((selected??0)+1).padStart(2,'0')} / 06</span><Button variant="ghost" size="icon" onClick={()=>step(1)} aria-label={t('Projet suivant','المشروع التالي')}><ArrowRight/></Button></div></>}</DialogContent></Dialog></>}
