import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import {Link,useSearch,useNavigate} from '@tanstack/react-router';
import {ArrowUpRight,Menu,X,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import logo from '@/assets/logo.png.asset.json';
import type {Language} from './content';
const LanguageContext=createContext<Language>('fr');
export const useLanguage=()=>useContext(LanguageContext);
export const useText=()=>{const lang=useLanguage();return (fr:string,ar:string)=>lang==='ar'?ar:fr};
export function Site({children}:{children:ReactNode}){
 const search=useSearch({strict:false}) as {lang?:Language}; const lang=search.lang||'fr'; const navigate=useNavigate(); const [menu,setMenu]=useState(false);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';localStorage.setItem('djouri-language',lang)},[lang]);
 const t=(fr:string,ar:string)=>lang==='ar'?ar:fr;
 const nav=[['/','Accueil','الرئيسية'],['/projets','Projets','المشاريع'],['/atelier','Notre atelier','مكتبنا'],['/contact','Contact','اتصل بنا']] as const;
 return <LanguageContext.Provider value={lang}><div dir={lang==='ar'?'rtl':'ltr'} className="site-shell"><header className="site-header"><Link to="/" search={{lang}} className="brand" aria-label="DJOURI DESIGNE — Accueil"><img src={logo.url} alt="DJOURI DESIGNE"/><span>ATELIER D’ARCHITECTURE</span></Link><nav aria-label={t('Navigation principale','التنقل الرئيسي')} className={menu?'main-nav is-open':'main-nav'}>{nav.map(([to,fr,ar])=><Link key={to} to={to} search={{lang}} activeOptions={{exact:true}} onClick={()=>setMenu(false)}>{t(fr,ar)}</Link>)}</nav><div className="header-actions"><div className="language-switch" aria-label="Language">{(['fr','ar'] as const).map((value)=><Button variant="ghost" key={value} className={lang===value?'language active':'language'} onClick={()=>navigate({to:'.',search:{lang:value}})} aria-pressed={lang===value}>{value==='fr'?'FR':'AR'}</Button>)}</div><Button variant="ghost" size="icon" className="mobile-menu" aria-label={t('Ouvrir le menu','فتح القائمة')} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div></header><main>{children}</main><footer className="site-footer"><div className="footer-brand"><img className="footer-logo" src={logo.url} alt="DJOURI DESIGNE"/><span>{t('Atelier d’architecture','مكتب الهندسة المعمارية')}</span></div><p>{t('© 2026 DJOURI DESIGNE. Tous droits réservés.','© 2026 ديجوري ديزاين. جميع الحقوق محفوظة.')}</p><Link to="/contact" search={{lang}}>{t('Parlons de votre projet','لنتحدث عن مشروعك')}<ArrowUpRight size={16}/></Link></footer></div></LanguageContext.Provider>
}
export function SectionHeading({number,title,subtitle,link=false}:{number:string,title:string,subtitle?:string,link?:boolean}){const lang=useLanguage();const t=useText();return <div className="section-heading"><div><span className="eyebrow">{number} / {t('L’EXIGENCE DU DÉTAIL','الدقة في التفاصيل')}</span><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{link&&<Link to="/projets" search={{lang}} className="text-link">{t('Tous les projets','كل المشاريع')}<ArrowUpRight size={18}/></Link>}</div>}
export function StudioSection({full=false}:{full?:boolean}){const lang=useLanguage();const t=useText();return <section className="studio-section section-wrap"><div className="studio-copy"><span className="eyebrow">02 / {t('NOTRE ATELIER','مكتبنا')}</span><h2>{t('Des espaces pensés.\nDes émotions vécues.','فضاءات مدروسة.\nتجارب ملموسة.')}</h2><p>{t('Nous croyons qu’une architecture juste naît d’un dialogue entre le lieu, la matière et celles et ceux qui l’habitent.','نؤمن بأن العمارة المتوازنة تنشأ من حوار بين المكان والمادة ومن يعيشون فيه.')}</p><p>{t('DJOURI DESIGNE accompagne chaque projet avec une même exigence : donner du sens aux volumes, révéler la lumière et créer des espaces qui vous ressemblent. De l’architecture au design intérieur, notre approche associe précision technique et sensibilité.','يرافق ديجوري ديزاين كل مشروع بنفس الالتزام: إعطاء معنى للأحجام وإبراز الضوء وابتكار فضاءات تعكس شخصيتكم. نجمع بين الدقة التقنية والحس الإبداعي في العمارة والتصميم الداخلي.')}</p>{full?<div className="expertise-list">{[t('Architecture & structure','العمارة والإنشاء'),t('Design intérieur','التصميم الداخلي'),t('Planification & études 3D','التخطيط والدراسات ثلاثية الأبعاد')].map((item,i)=><div key={item}><span>0{i+1}</span>{item}</div>)}</div>:<Link to="/atelier" search={{lang}} className="text-link">{t('Découvrir l’atelier','اكتشف مكتبنا')}<ArrowRight size={18}/></Link>}</div><div className="studio-visual"><img src={studioImage} loading="lazy" alt={t('Étude d’un intérieur aux lignes précises','دراسة تصميم داخلي بخطوط دقيقة')}/><span>{t('Une vision. De la première esquisse au dernier détail.','رؤية واحدة. من أول رسم إلى أدق التفاصيل.')}</span></div></section>}
import {studioImage} from './content';
