/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProjetsRouteImport } from './routes/projets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/contact': typeof ContactRoute
  '/projets': typeof ProjetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/contact': typeof ContactRoute
  '/projets': typeof ProjetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/contact': typeof ContactRoute
  '/projets': typeof ProjetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atelier' | '/contact' | '/projets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atelier' | '/contact' | '/projets'
  id: '__root__' | '/' | '/atelier' | '/contact' | '/projets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  ContactRoute: typeof ContactRoute
  ProjetsRoute: typeof ProjetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  ContactRoute: ContactRoute,
  ProjetsRoute: ProjetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
